defaults:
  - base
  - _self_

project: llama_finetune

# Lightning Trainer
trainer:
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  gradient_clip_algorithm: 'norm'

# Dataset Configuration
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: fishaudio/speech-lm-300m
  revision: text-pretrain-10k

# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.text.InterleaveDataset
  datasets:
    - _target_: fish_speech.datasets.text.TextDataset
      prefix: 'en/'
    - _target_: fish_speech.datasets.text.TextDataset
      prefix: 'zh/'
    - _target_: fish_speech.datasets.text.TextDataset
      prefix: 'ja/'
    - _target_: fish_speech.datasets.text.TextDataset
      repo: fishaudio/cn-hubert-25hz-vq
      prefix: 'data/train'
  probabilities: [0.2, 0.2, 0.2, 0.4]
  seed: 42

val_dataset:
  _target_: fish_speech.datasets.text.TextDataset
  repo: fishaudio/cn-hubert-25hz-vq
  prefix: 'data/test'

data:
  _target_: fish_speech.datasets.text.TextDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 1
  batch_size: 8
  tokenizer: ${tokenizer}

# Model Configuration
model:
  _target_: fish_speech.models.text2semantic.TextToSemantic

  model:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: fishaudio/speech-lm-300m
    revision: text-pretrain-10k

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1e-4
    weight_decay: 0.1
    betas: [0.9, 0.95]
    eps: 1e-5

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
    lr_lambda:
      _target_: fish_speech.scheduler.get_cosine_schedule_with_warmup_lr_lambda
      _partial_: true
      num_warmup_steps: 2000
      num_training_steps: ${trainer.max_steps}
      final_lr_ratio: 0.1
