site_name: Fish Speech
repo_url: https://github.com/fishaudio/fish-speech

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - search
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      font:
        code: Roboto Mono

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      font:
        code: Roboto Mono
  
extra:
  homepage: https://speech.fish.audio
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
